
-- Alter tables
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS uom TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit_price NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_quantity NUMERIC;

ALTER TABLE raw_materials ADD COLUMN IF NOT EXISTS unit_price NUMERIC;
ALTER TABLE raw_materials ADD COLUMN IF NOT EXISTS stock_quantity NUMERIC;

-- Raw Materials & Packaging
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Baby Mushrooms', 1, 4)), 'Baby Mushrooms', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Bumbu Tabur Balado', 1, 4)), 'Bumbu Tabur Balado', 'gram', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Bumbu Tabur Barbeque', 1, 4)), 'Bumbu Tabur Barbeque', 'gram', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Bumbu Tabur Pedas Manis', 1, 4)), 'Bumbu Tabur Pedas Manis', 'gram', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Bumbu Tabur Super Pedas', 1, 4)), 'Bumbu Tabur Super Pedas', 'gram', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Gagang Jamur', 1, 4)), 'Gagang Jamur', 'gram', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Honeysia - Honey Barbeque - 60 gr', 1, 4)), 'Honeysia - Honey Barbeque - 60 gr', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Honeysia - Honey Mentai - 60 gr', 1, 4)), 'Honeysia - Honey Mentai - 60 gr', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Honeysia - Honey Mustrad - 60 gr', 1, 4)), 'Honeysia - Honey Mustrad - 60 gr', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Jamur Tiram', 1, 4)), 'Jamur Tiram', 'kg', 'Bahan Baku', 15000, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('KHUM KHUM JAMUR CRISPY BALADO PCH 60g', 1, 4)), 'KHUM KHUM JAMUR CRISPY BALADO PCH 60g', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('KHUM KHUM JAMUR CRISPY BARBEQUE PCK 60g', 1, 4)), 'KHUM KHUM JAMUR CRISPY BARBEQUE PCK 60g', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('KHUM KHUM JAMUR CRISPY ORIGINAL PCH 60g', 1, 4)), 'KHUM KHUM JAMUR CRISPY ORIGINAL PCH 60g', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('KHUM KHUM JAMUR CRISPY PEDAS MANIS PCH 60g', 1, 4)), 'KHUM KHUM JAMUR CRISPY PEDAS MANIS PCH 60g', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Kemasan Bantal Alumunium', 1, 4)), 'Kemasan Bantal Alumunium', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Minyak Goreng', 1, 4)), 'Minyak Goreng', 'liter', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Minyak Jelantah', 1, 4)), 'Minyak Jelantah', 'liter', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Packaging', 1, 4)), 'Packaging', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Packaging Balado 75 Gram', 1, 4)), 'Packaging Balado 75 Gram', 'pcs', 'Bahan Baku', 2350, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Packaging Barbeque 60 Gram', 1, 4)), 'Packaging Barbeque 60 Gram', 'pcs', 'Bahan Baku', 2400, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Packaging Barbeque 75 Gram', 1, 4)), 'Packaging Barbeque 75 Gram', 'pcs', 'Bahan Baku', 2350, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Packaging Original 60 Gram', 1, 4)), 'Packaging Original 60 Gram', 'pcs', 'Bahan Baku', 2400, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Packaging Original 75 Gram', 1, 4)), 'Packaging Original 75 Gram', 'pcs', 'Bahan Baku', 2350, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Packaging Pedas Manis 75 Gram', 1, 4)), 'Packaging Pedas Manis 75 Gram', 'pcs', 'Bahan Baku', 2350, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Packaging Super Pedas 75 Gram', 1, 4)), 'Packaging Super Pedas 75 Gram', 'pcs', 'Bahan Baku', 2350, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Paket Bumbu', 1, 4)), 'Paket Bumbu', 'buah', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Segel Plastik', 1, 4)), 'Segel Plastik', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Tepung Terigu', 1, 4)), 'Tepung Terigu', 'kg', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Toples 500 Gram', 1, 4)), 'Toples 500 Gram', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO raw_materials (id, code, name, uom, material_category, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'RM-' || upper(substr('Toples 800 ml', 1, 4)), 'Toples 800 ml', 'pcs', 'Bahan Baku', 0, 0) ON CONFLICT DO NOTHING;

-- Finished Goods
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Ahaii Balado', 1, 4)), 'Ahaii Balado', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Ahaii Barbeque', 1, 4)), 'Ahaii Barbeque', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Ahaii Original', 1, 4)), 'Ahaii Original', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Ahaii Pedas Manis', 1, 4)), 'Ahaii Pedas Manis', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Ahaii Super Pedas', 1, 4)), 'Ahaii Super Pedas', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('KhumKhum Balado', 1, 4)), 'KhumKhum Balado', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('KhumKhum Barbeque', 1, 4)), 'KhumKhum Barbeque', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('KhumKhum Original', 1, 4)), 'KhumKhum Original', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('KhumKhum Pedas Manis', 1, 4)), 'KhumKhum Pedas Manis', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('KhumKhum Super Pedas', 1, 4)), 'KhumKhum Super Pedas', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Maklon Crispy Mushrooms Balado', 1, 4)), 'Maklon Crispy Mushrooms Balado', 'Barang Jadi', 'kg', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Maklon Crispy Mushrooms Barbeque', 1, 4)), 'Maklon Crispy Mushrooms Barbeque', 'Barang Jadi', 'kg', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Maklon Crispy Mushrooms Original', 1, 4)), 'Maklon Crispy Mushrooms Original', 'Barang Jadi', 'kg', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Maklon Crispy Mushrooms Pedas Manis', 1, 4)), 'Maklon Crispy Mushrooms Pedas Manis', 'Barang Jadi', 'kg', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Maklon Crispy Mushrooms Super Pedas', 1, 4)), 'Maklon Crispy Mushrooms Super Pedas', 'Barang Jadi', 'kg', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum 500 Gr - Balado', 1, 4)), 'Masnum 500 Gr - Balado', 'Barang Jadi', 'buah', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum 500 Gr - Barbeque', 1, 4)), 'Masnum 500 Gr - Barbeque', 'Barang Jadi', 'buah', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum 500 Gr - Original', 1, 4)), 'Masnum 500 Gr - Original', 'Barang Jadi', 'buah', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum 500 Gr - Pedas Manis', 1, 4)), 'Masnum 500 Gr - Pedas Manis', 'Barang Jadi', 'buah', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum 500 Gr - Super Pedas', 1, 4)), 'Masnum 500 Gr - Super Pedas', 'Barang Jadi', 'buah', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Balado', 1, 4)), 'Masnum Balado', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Bantal Balado', 1, 4)), 'Masnum Bantal Balado', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Bantal Barbeque', 1, 4)), 'Masnum Bantal Barbeque', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Bantal Original', 1, 4)), 'Masnum Bantal Original', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Bantal Pedas Manis', 1, 4)), 'Masnum Bantal Pedas Manis', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Bantal Super Pedas', 1, 4)), 'Masnum Bantal Super Pedas', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Barbeque', 1, 4)), 'Masnum Barbeque', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Jamur Crispy', 1, 4)), 'Masnum Jamur Crispy', 'Barang Jadi', 'buah', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Original', 1, 4)), 'Masnum Original', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Pedas Manis', 1, 4)), 'Masnum Pedas Manis', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Masnum Super Pedas', 1, 4)), 'Masnum Super Pedas', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO products (id, sku, name, category, uom, unit_price, stock_quantity) VALUES (gen_random_uuid(), 'SKU-' || upper(substr('Toples Masnum', 1, 4)), 'Toples Masnum', 'Barang Jadi', 'pcs', 0, 0) ON CONFLICT DO NOTHING;
